### ISSUE TITLE
Build fails with `error[E0635]: unknown feature proc_macro_span_shrink`

### ISSUE THREAD

**Issue by tmaklin** [algbio/ggcat#31] opened 2023-07-04 16:17 UTC
Hi, I'm trying to build ggcat with rust 1.72.0-nightly (0ab38e95b 2023-07-03) but the build keeps failing with an error related to unknown features. I'm guessing this has something to do with the nightly issues mentioned in #27?
```
$ cargo install --path crates/cmdline/ --locked
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
  Installing ggcat_cmdline v0.1.0 (/home/temaklin/software/ggcat/crates/cmdline)
    Updating crates.io index
warning: package `hermit-abi v0.3.1` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
warning: package `pest v2.6.0` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
warning: Patch `papi-bindings v0.5.2 (/home/temaklin/software/ggcat/libs-crates/papi-bindings-rs)` was not used in the crate graph.
Check that the patched package version and available features are compatible
with the dependency requirements. If the patch has a different version from
what is locked in the Cargo.lock file, run `cargo update` to use the new
version. This may also occur with an optional dependency that is not enabled.
   Compiling proc-macro2 v1.0.59
   Compiling getrandom v0.2.9
   Compiling num-traits v0.2.15
   Compiling crossbeam-utils v0.8.15
   Compiling hashbrown v0.12.3
   Compiling lazy_static v1.4.0
   Compiling proc-macro-error-attr v1.0.4
   Compiling lock_api v0.4.9
   Compiling memoffset v0.8.0
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /home/temaklin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.59/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `proc-macro2` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `ggcat_cmdline v0.1.0 (/home/temaklin/software/ggcat/crates/cmdline)`, intermediate artifacts can be found at `/home/temaklin/software/ggcat/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by Guilucand** [comment] 2023-07-05 08:15
Hi, thanks for the report! I updated the project deps and the problem is now fixed

**Closed** 2023-07-05 08:14 UTC
